import PositionedSnackbar from "@/components/PositionedSnackbar";
import ThemeWrapper from "@/containers/ThemeWrapper";
import { PositionedSnackbarProvider } from "@/providers/positionedSnackbarProvider";
import { UserProvider } from "@/providers/userProvider";
import "@/styles/globals.css";
import Head from "next/head";

export default function StaticPageRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <link rel="manifest" href="/banking-web/manifest.json" />
        <link
          rel="icon"
          type="image/x-icon"
          href="/banking-web/pwa-icons/android-launchericon-512-512.png"
        />
        <title>Banking Web App</title>
        <meta name="description" content="Generated by Patrick Tse" />
      </Head>
      <ThemeWrapper>
        <UserProvider>
          <PositionedSnackbarProvider>
            <div className={`main`}>
              <PositionedSnackbar />
              {children}
            </div>
          </PositionedSnackbarProvider>
        </UserProvider>
      </ThemeWrapper>
    </>
  );
}
