import PositionedSnackbar from "@/components/PositionedSnackbar";
import ThemeWrapper from "@/containers/ThemeWrapper";
import { PositionedSnackbarProvider } from "@/providers/positionedSnackbarProvider";
import { UserProvider } from "@/providers/userProvider";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StrictMode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Banking Web App",
  description: "Generated by Patrick Tse",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StrictMode>
        <ThemeWrapper>
          <UserProvider>
            <PositionedSnackbarProvider>
              <body className={`${inter.className} main`}>
                <PositionedSnackbar />
                {children}
              </body>
            </PositionedSnackbarProvider>
          </UserProvider>
        </ThemeWrapper>
      </StrictMode>
    </html>
  );
}
