import ThemeWrapper from "@/containers/ThemeWrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Banking Web App",
  description: "Generated by Patrick Tse",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <ThemeWrapper>
        <body className={`${inter.className} main`}>{children}</body>
      </ThemeWrapper>
    </html>
  );
}
